# Generated by Django 6.0.2 on 2026-02-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('meetup', 'Meetup'), ('workshop', 'Workshop'), ('career_fair', 'Career fair'), ('networking', 'Networking'), ('webinar', 'Webinar')], db_index=True, max_length=20)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/%Y/%m/')),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('location', models.TextField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('registered_count', models.PositiveIntegerField(default=0)),
                ('waitlist_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('date', 'time'),
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No show')], default='registered', max_length=20)),
                ('is_waitlist', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event registration',
                'verbose_name_plural': 'Event registrations',
                'ordering': ('-registered_at',),
            },
        ),
    ]
