# Generated by Django 6.0.2 on 2026-02-26 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFairRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Career fair registration',
                'verbose_name_plural': 'Career fair registrations',
                'ordering': ('-registered_at',),
            },
        ),
        migrations.CreateModel(
            name='CareerFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_start', models.DateField(db_index=True)),
                ('date_end', models.DateField(db_index=True)),
                ('location', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='career_fairs/banners/%Y/%m/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('max_companies', models.PositiveIntegerField()),
                ('registered_companies_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Career fair',
                'verbose_name_plural': 'Career fairs',
                'ordering': ('-date_start',),
                'indexes': [models.Index(fields=['is_active'], name='career_fair_is_acti_7babf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareerFairCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='career_fairs.careerfair')),
            ],
            options={
                'verbose_name': 'Career fair company',
                'verbose_name_plural': 'Career fair companies',
                'ordering': ('career_fair', 'booth_number'),
            },
        ),
    ]
