# Generated by Django 6.0.2 on 2026-02-26 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career_fairs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careerfairregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_fair_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='careerfaircompany',
            unique_together={('career_fair', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='careerfairregistration',
            unique_together={('user', 'career_fair')},
        ),
    ]
