# Generated by Django 6.0.2 on 2026-02-26 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='companies', through='companies.CompanyUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='companies.company'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='job_postings', to='skills.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='companyuser',
            unique_together={('user', 'company')},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_verified'], name='companies_c_is_veri_542ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='companies_c_industr_6efa2c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['is_active'], name='companies_j_is_acti_eee78a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['-published_at'], name='companies_j_publish_092477_idx'),
        ),
    ]
