# Generated by Django 5.2.13 on 2026-04-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approved_for_talents_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_approved_for_talents',
            field=models.BooleanField(default=False, help_text='Админ разрешил компании доступ к verified участникам.'),
        ),
    ]
