# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_approved_for_talents_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="apply_url",
            field=models.URLField(
                blank=True,
                help_text="External application URL on the employer website.",
                max_length=500,
            ),
        ),
    ]
