# Generated by Django 5.2.14 on 2026-05-13 06:22

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_url',
            field=models.FileField(blank=True, null=True, upload_to='jobs/resumes/%Y/%m/', validators=[apps.common.validators.validate_pdf_upload]),
        ),
    ]
