# Generated by Django 6.0.2 on 2026-03-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Показывается на странице новости сверху. Необязательно.', null=True, upload_to='home/news/%Y/%m/', verbose_name='Картинка новости'),
        ),
    ]
