# Generated by Django 6.0.2 on 2026-03-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_allow_null_email'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mentorprofile',
            name='users_mento_is_avai_f84f77_idx',
        ),
        migrations.RemoveIndex(
            model_name='mentorprofile',
            name='users_mento_rating_ad5c85_idx',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_role_36d76d_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/profiles/%Y/%m/'),
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfessionalProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='MentorProfile',
        ),
    ]
