# Generated by Django 5.2.13 on 2026-04-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_add_is_presence_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Резюме / CV участника (PDF).', null=True, upload_to='users/cv/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_user',
            field=models.BooleanField(default=False, help_text='Пользователь является представителем компании.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Верифицированный участник (автоматически после 3 посещённых митапов).'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='users_user_is_veri_9ce429_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_company_user'], name='users_user_is_comp_e51077_idx'),
        ),
    ]
