# Generated by Django 5.2.14 on 2026-05-13 06:22

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_cv_file_user_is_company_user_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Резюме / CV участника (PDF).', null=True, upload_to='users/cv/%Y/%m/', validators=[apps.common.validators.validate_pdf_upload]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/profiles/%Y/%m/', validators=[apps.common.validators.validate_image_upload]),
        ),
    ]
