# Generated by Django 5.2.13 on 2026-04-15 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='jobs.jobapplication')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('company_user', models.ForeignKey(help_text='Company-side user who manages this chat.', on_delete=django.db.models.deletion.CASCADE, related_name='company_chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat room',
                'verbose_name_plural': 'Chat rooms',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
            ],
            options={
                'verbose_name': 'Chat message',
                'verbose_name_plural': 'Chat messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='InterviewInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(help_text='Дата и время интервью.')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Длительность в минутах.')),
                ('format', models.CharField(choices=[('online', 'Online (Zoom/Google Meet)'), ('offline', 'Offline (в офисе)'), ('phone', 'По телефону')], default='online', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Zoom-ссылка или адрес офиса.', max_length=500)),
                ('note', models.TextField(blank=True, help_text='Дополнительная информация от компании.')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Подтверждено'), ('declined', 'Отклонено'), ('rescheduled', 'Перенесено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=20)),
                ('candidate_comment', models.TextField(blank=True, help_text='Комментарий кандидата (при переносе/отклонении).')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='chat.chatroom')),
            ],
            options={
                'verbose_name': 'Interview invite',
                'verbose_name_plural': 'Interview invites',
                'ordering': ('-scheduled_at',),
            },
        ),
    ]
